### ISSUE TITLE
Module #8 - Data Citation

### ISSUE THREAD

**Issue by whshannon** [DataONEorg/dataone_lessons#36] opened 2016-09-22 15:41 UTC
I'm working on migrating the PPT to markdown.

**Comment by hsoyka** [comment] 2016-12-07 23:28
- [ ]     Transfer all text content to the slides
- [ ]     Compare text transferred to most recent ppt - ensure it's current
- [ ]     Re-export images - rework images to ensure high quality graphics in the presentation
- [ ]     Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ]      Review edits and changes to final slides, read for clarity/images positioned properly.

**Comment by whshannon** [comment] 2016-12-21 19:24
- [X]  Transfer all text content to the slides
- [X]  Compare text transferred to most recent ppt - ensure it's current
- [X]  Re-export images - rework images to ensure high quality graphics in the presentation
- [X]  Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ]  Review edits and changes to final slides, read for clarity/images positioned properly

Only the last item still needs work. There are words and images that run off the slides... not sure if this is something that can be managed in the css, or if the content needs to be split up to multiple slides.

**Comment by aebudden** [comment] 2017-04-07 02:48
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.

**Closed by aebudden** 2017-04-07 02:48 UTC
